defaults:
  - default.yaml

score_configs:
  model_name: 'ddpm'
  ch: 64
  ch_mult: [1, 2, 2, 2]
  attn: [1]
  num_res_blocks: 4
  dropout: 0.1

sde_configs:
  sde_name: 'subVPSDE'
  beta_0: 0.1
  beta_1: 20
  N: 1000

sampler_configs:
  predictor_name: 'euler-maruyama'
  corrector_name: 'none'
  snr: 'subVPSDE'
  n_steps: 1
  noise_removal: True

on_white_background: False
on_black_background: False
err_quantile: 0.2