defaults:
  - sbm_default.yaml

score_configs:
  model_name: 'ddpm'
  sigma_0: 0.01
  sigma_1: 50.
  num_scales: 1000
  beta_0: 0.1
  beta_1: 20.
  dropout: 0.1
  scal_by_sigma: False
  ema_rate: 0.9999
  normalization: 'GroupNorm'
  nonlinearity: 'swish'
  nf: 128
  ch_mult: (1, 2, 2, 2)
  num_res_blocks: 2
  attn_resolutions: (16,)
  resamp_with_conv: True
  conditional: True
  fir: False
  fir_kernel: (1, 3, 3, 1)
  skip_rescale: True
  resblock_type: 'biggan'
  progressive: 'none'
  progressive_input: 'none'
  progressive_combine: 'sum'
  attention_type: 'ddpm'
  embedding_type: 'positional'
  init_scale: 0.
  fourier_scale: 16
  conv_size: 3

sde_configs:
  sde_name: 'subVPSDE'
  beta_0: 0.1,
  beta_1: 20,
  N: 2000,